// "What's new" — the plain-language changelog for members. The roadmap's
// release notes only cover items someone filed on the roadmap, so most of
// what shipped never reached anyone. Add new items at the TOP; the first
// item's id is what the unread dot compares against.
//
// `href` may contain {username}, replaced with the signed-in member's name.

export interface WhatsNewItem {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  body: string;
  howTo?: string;
  href?: string;
  cta?: string;
  tag?: "Writing" | "Reading" | "Letters" | "Profile" | "Fediverse" | "Mobile" | "Plus";
}

export const WHATS_NEW: WhatsNewItem[] = [
  {
    id: "2026-09-25-app-feel",
    date: "2026-09-25",
    title: "The Inkwell app: share into it, a proper launch screen, and tilt",
    body: "If you've added Inkwell to your home screen: on Android you can now share a link or text from any app straight into Inkwell and jot it as a sticky or start an entry with it. On iPhone and iPad the app opens on an Inkwell launch screen (light or dark, to match your phone) instead of a blank white one. And there's an optional touch of fun: turn on Tilt effects and stamps, archive postmarks and avatar frames shift and catch the light as you tilt your phone.",
    howTo: "Share: use your phone's Share menu and pick Inkwell. Tilt: Settings → Look & feel → Tilt effects.",
    href: "/settings/look",
    cta: "Look & feel",
    tag: "Mobile",
  },
  {
    id: "2026-09-25-mobile-polish",
    date: "2026-09-25",
    title: "Phones: short posts look like pages, and a round of small fixes",
    body: "A post of a few lines used to sit at the top of a tall, mostly empty card on a phone. Now it's set in the middle of the page in larger type, like a short poem in a book. Also: bigger buttons in the editor, comments and letters; pop-up menus stay above the keyboard and close with Escape; quoted posts no longer scroll inside the page; tap a day in Readers to see its count; long fediverse handles wrap; and sheets fit iPhone screens properly.",
    tag: "Mobile",
  },
  {
    id: "2026-09-25-mobile-scroll",
    date: "2026-09-25",
    title: "Phones: no more getting stuck in a post",
    body: "On a phone, scrolling inside a long entry on Feed or Explore could trap you there until you touched the top of the screen. Now a swipe carries on to the page when you reach the end of an entry, and turning to the next post takes any swipe that's more sideways than up-and-down, with the page following your finger. Also: iPhones no longer zoom in when you tap a text box, the keyboard no longer covers the Send button in letters and comments, the Ink, Stamp, Bookmark and Share buttons are easier to tap, and you can pull down to refresh on every page.",
    howTo: "Close the comment sheet by dragging its handle down.",
    tag: "Mobile",
  },
  {
    id: "2026-09-24-tidier-sidebar",
    date: "2026-09-24",
    title: "A tidier sidebar",
    body: "The sidebar had grown to about thirty rows. Now it holds the places you go, in four short sections (Read, Correspondence, Your journal, Community), and each section folds up and remembers it. Everything about you (your journal page, Settings, Modern or Classic look, What’s new, Help, Invite friends, Sign out) is in one menu that opens from your name at the bottom.",
    howTo: "Click your name at the bottom of the sidebar. Click a section’s heading to fold it. If you hide the sidebar, a Menu button at the top left brings it back. Only one notice now sits above your Feed at a time.",
    tag: "Reading",
  },
  {
    id: "2026-09-24-userpics",
    date: "2026-09-24",
    title: "Userpics: a picture for every mood",
    body: "Keep a set of pictures, each with a keyword (“coffee”, “rainy day”), and choose one for each entry and each footnote. It shows beside that entry or footnote in place of your avatar, and big in Classic view. Animated GIFs keep moving. Your avatar stays the default. Free accounts get 10 userpics, Plus 50.",
    howTo: "Settings → Userpics to add them. Then pick one with the little picture at the start of the editor’s mood line, or “Posting as” above the footnote box.",
    href: "/settings/userpics",
    cta: "Add userpics",
    tag: "Profile",
  },
  {
    id: "2026-09-24-share-previews",
    date: "2026-09-24",
    title: "Your writing shows up when you share it",
    body: "Share an entry on Facebook, iMessage, Slack, LinkedIn or Bluesky and the preview now shows a page with your title, the opening lines, your name and picture, instead of a bare link. Stickies show up as a sticky note in their own colour. A cover photo, if you added one, is still used. Posts behind a content warning show only the warning, and private posts never show their words.",
    howTo: "Nothing to do: share any public entry. If Facebook still shows an old preview for a link you shared before, paste it into Facebook’s Sharing Debugger and press “Scrape Again”.",
    tag: "Writing",
  },
  {
    id: "2026-09-24-classic-view",
    date: "2026-09-24",
    title: "Classic view: Inkwell the 2004 way",
    body: "Turn on Classic view and Feed and Explore become one long column of boxed entries, the way journals looked in 2004: big userpics, the username bar with the date, “Subject:”, Current mood / music / location, and “( 3 comments | Leave a comment )”. The rest of the site switches to the colours and type of the early-2000s web, in light and dark. Only you see it, and you can switch back any time.",
    howTo: "Click your name at the bottom of the sidebar and set Look to Classic (on your phone: You → Look), or Settings → Look & feel.",
    href: "/settings/look",
    cta: "Choose your look",
    tag: "Reading",
  },
  {
    id: "2026-09-24-moods",
    date: "2026-09-24",
    title: "Moods have faces again",
    body: "Your mood now comes with a little animated face: pick from over 130 moods, or write your own words and keep the face beside them. Choose Classic pixel smileys or hand-drawn Ink faces for your journal. Entries now show a “Current mood / Current music / Current location” block under the title, and older entries get faces from the moods you already wrote. LiveJournal imports now bring back moods picked from LJ’s list, and your location.",
    howTo: "In the editor, click “your mood…” next to “feeling”. The icon style switch is at the bottom of the list. The pin beside it is for your location.",
    href: "/editor",
    cta: "Write an entry",
    tag: "Writing",
  },
  {
    id: "2026-09-24-fediverse-credit-guestbook",
    date: "2026-09-24",
    title: "Mastodon now credits you when your entries are shared",
    body: "When someone shares a link to one of your entries on Mastodon, the preview card now names you, with a link to your fediverse profile, so readers can follow you from there. This works for your own domain too. Your guestbook is also now a standard fediverse guestbook: any fediverse app that supports it can sign it directly. Replying to your guestbook post from Mastodon still works as before.",
    tag: "Fediverse",
  },
  {
    id: "2026-09-24-circles",
    date: "2026-09-24",
    title: "Circles are now threads you write into",
    body: "A circle is now a list of threads. Start one with an ordinary journal entry, and members answer it with entries of their own. Every answer appears under the thread and stays on its writer’s journal, and posts can be public or for circle members only. Owners can pin a thread as the circle’s prompt. And anyone whose account is a week old can start a circle, not just Plus members.",
    howTo: "Circles in the sidebar (or You → Circles on your phone). Join one, press “New thread”, or open a thread and press “Write your answer”.",
    href: "/circles",
    cta: "Find a circle",
    tag: "Writing",
  },
  {
    id: "2026-09-24-gazette",
    date: "2026-09-24",
    title: "A new Gazette: the news the fediverse is sharing, twice a day",
    body: "The Gazette is now a real paper: a morning and an evening edition of the articles people across the fediverse are sharing most, ranked by how many people shared them. No algorithm, no AI. Open any story to see what people are saying about it, and press “Write about this” to answer it in your journal. Your entry shows up beside the story.",
    howTo: "Gazette in the sidebar (or You → Gazette on your phone). Follow a section to put it first.",
    href: "/gazette",
    cta: "Read today’s paper",
    tag: "Reading",
  },
  {
    id: "2026-09-24-schedule-button",
    date: "2026-09-24",
    title: "Schedule a post right from the Publish button",
    body: "Next to Publish there's now a clock. Pick “Tomorrow morning”, “Saturday morning” or any time you like, then press Schedule and the entry publishes itself.",
    href: "/editor",
    cta: "Open the editor",
    tag: "Writing",
  },
  {
    id: "2026-09-24-phone-filters",
    date: "2026-09-24",
    title: "Feed and Explore get to the writing faster on phones",
    body: "Filters (source, sort and topics) now fold behind a single row that tells you what's showing, so the first entry is on screen when the page opens.",
    tag: "Mobile",
  },
  {
    id: "2026-09-24-guestbook-notifications",
    date: "2026-09-24",
    title: "Know when someone signs your guestbook",
    body: "Guestbook signatures from other Inkwell members now arrive as notifications (and push, if you've turned it on), with a preview of what they wrote. Before, only signatures from Mastodon did.",
    href: "/{username}#guestbook",
    cta: "Visit your guestbook",
    tag: "Profile",
  },
  {
    id: "2026-09-24-fediverse-letters",
    date: "2026-09-24",
    title: "Letters with your Mastodon friends",
    body: "You can now write private letters to fediverse accounts you follow or that follow you, and their private messages to you land in Letters instead of your notifications.",
    howTo: "In Letters, press New letter — fediverse pen pals are marked “fediverse”.",
    href: "/letters",
    cta: "Open Letters",
    tag: "Letters",
  },
  {
    id: "2026-09-24-magazine",
    date: "2026-09-24",
    title: "A real Magazine layout for your profile",
    body: "Your newest story becomes a cover story with a drop cap, the rest flow in newspaper columns, and there's a contents rail. Great for journals with years of entries.",
    howTo: "Settings → Customize → Layout → Magazine.",
    href: "/settings/customize",
    cta: "Try Magazine",
    tag: "Plus",
  },
  {
    id: "2026-09-23-letters-controls",
    date: "2026-09-23",
    title: "Letters got a lot better",
    body: "A reply bar at the bottom of every conversation, drafts that survive closing the page, archive, mute, mark as unread, and search inside your letters. You can also choose to accept letter requests from people who aren't your pen pals yet.",
    howTo: "Use the ⋯ menu on a conversation, or “Who can write to you” in Letters.",
    href: "/letters",
    cta: "Open Letters",
    tag: "Letters",
  },
  {
    id: "2026-09-23-translate",
    date: "2026-09-23",
    title: "Translate any entry in one click",
    body: "Reading someone who writes in Spanish, Russian or Chinese? Every entry page now has a Translate button above the text, and the title translates too.",
    howTo: "Set your language once in Settings → Profile for one-click translation.",
    tag: "Reading",
  },
  {
    id: "2026-09-23-archive-postmark",
    date: "2026-09-23",
    title: "Old posts can wear an archive postmark",
    body: "Brought your old journal over? Mark those posts as from your archive: a postmark on the card, and a paper-clipped note on the page saying when you first wrote it — in your own words if you like.",
    href: "/settings/import#archive",
    cta: "Your archive settings",
    tag: "Writing",
  },
  {
    id: "2026-09-22-readers",
    date: "2026-09-22",
    title: "See how many people read you",
    body: "Reader counts, counted privately (no tracking, no cookies): a reader is someone who actually stayed on your entry for ten seconds. Everyone sees totals; Plus adds a daily chart, top entries and where readers came from.",
    href: "/readers",
    cta: "See your readers",
    tag: "Writing",
  },
  {
    id: "2026-09-22-livejournal",
    date: "2026-09-22",
    title: "Bring your LiveJournal or Dreamwidth over",
    body: "Import your whole journal — with comments, moods and music — from an export file. Lost your LiveJournal password? You can still bring over your public entries.",
    href: "/switch/livejournal",
    cta: "How to move",
    tag: "Writing",
  },
  {
    id: "2026-09-22-profile-archive",
    date: "2026-09-22",
    title: "Browse a journal by year and month",
    body: "Profiles now have an archive: pick a year, then a month, instead of clicking Next page after page. Entry pages have Older / Newer links too.",
    tag: "Profile",
  },
  {
    id: "2026-09-22-mobile",
    date: "2026-09-22",
    title: "A better Inkwell on your phone",
    body: "Double-tap a page to ink it. Write opens a choice of a full entry or a quick sticky. Everything else lives under the You tab — including “Install the app” to put Inkwell on your home screen.",
    tag: "Mobile",
  },
  {
    id: "2026-09-22-media",
    date: "2026-09-22",
    title: "Videos and audio from the fediverse play here",
    body: "Posts from Mastodon, Pixelfed, PeerTube and Threads that include video or audio now play right in your Feed and Explore instead of showing only the caption.",
    tag: "Fediverse",
  },
  {
    id: "2026-09-21-bluesky",
    date: "2026-09-21",
    title: "Share your journal on Bluesky",
    body: "One switch puts your public entries on Bluesky too, through Bridgy Fed, so Bluesky readers can follow you there.",
    href: "/settings/fediverse",
    cta: "Turn it on",
    tag: "Fediverse",
  },
  {
    id: "2026-09-21-popups",
    date: "2026-09-21",
    title: "Notifications pop up as they arrive",
    body: "New comments, stamps and letters now appear in the corner while you're on Inkwell, with a soft chime. You can turn the pop-ups or the sound off.",
    href: "/settings/notifications",
    cta: "Notification settings",
    tag: "Reading",
  },
  {
    id: "2026-09-20-avatars",
    date: "2026-09-20",
    title: "Hand-drawn avatars",
    body: "Don't want to use a photo? Build a little ink-drawn alien — hundreds of thousands of combinations, with books, tea, candles and quills.",
    href: "/settings/avatar",
    cta: "Build yours",
    tag: "Profile",
  },
  {
    id: "2026-09-19-stickies",
    date: "2026-09-19",
    title: "Stickies: short thoughts",
    body: "Not everything needs a title. Jot a sticky (up to 500 characters) — it shows on your profile's corkboard and in Feed, and goes to Mastodon in full. Any sticky can grow into a full entry later.",
    howTo: "“Jot a sticky” under Write in the sidebar, or Write → Sticky on your phone.",
    href: "/{username}",
    cta: "See your corkboard",
    tag: "Writing",
  },
  {
    id: "2026-09-19-scheduled",
    date: "2026-09-19",
    title: "Schedule posts for later",
    body: "Write now, publish Tuesday at 9am. Scheduled posts go out on their own — including your newsletter and cross-posts.",
    howTo: "Use the clock next to Publish in the editor. Publish becomes Schedule.",
    href: "/editor",
    cta: "Open the editor",
    tag: "Writing",
  },
  {
    id: "2026-09-19-dates",
    date: "2026-09-19",
    title: "Change the date on any entry",
    body: "Backdate an entry to when you actually wrote it, or fix the date on an imported post. It moves to the right place on your profile.",
    howTo: "Editor → Settings → Date.",
    tag: "Writing",
  },
  {
    id: "2026-09-19-bulk",
    date: "2026-09-19",
    title: "Tidy up many posts at once",
    body: "The Posts page lets you select any number of entries and change privacy, category, series or tags, publish drafts, or delete — handy after an import.",
    href: "/manage",
    cta: "Open Posts",
    tag: "Writing",
  },
  {
    id: "2026-09-19-fedi-media-links",
    date: "2026-09-19",
    title: "PeerTube, Funkwhale and Castopod links play",
    body: "Paste a link from an independent video, music or podcast server into an entry's “listening to” field and it becomes a player.",
    tag: "Fediverse",
  },
  {
    id: "2026-09-17-founding",
    date: "2026-09-17",
    title: "Try Plus free for 14 days",
    body: "No card needed. Plus is also available yearly ($50), and the first 50 Founding Members get Plus for as long as Inkwell runs.",
    href: "/settings/billing",
    cta: "See Plus",
    tag: "Plus",
  },
];

export const LATEST_WHATS_NEW_ID = WHATS_NEW[0].id;

export function whatsNewHref(href: string | undefined, username: string | null | undefined): string | null {
  if (!href) return null;
  if (href.includes("{username}")) return username ? href.replace("{username}", username) : null;
  return href;
}
